[package]
name = "aero-traffic-control"
version = "0.4.1"
edition = "2024"

[dependencies]
thiserror = "2"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
